.TH nest-home 1 "31 December 2014" uhome "uhome"
.SH NAME
nest-home \- sets your Nest to note that you're currently at home

nest-away \- sets your Nest to note that you're currently away from home

.SH SYNOPSIS
\fBnest-home\fP

\fBnest-away\fP

.SH OPTIONS
Note that the environment variables \fBNEST_USERNAME\fP and \fBNEST_PASSWORD\fP must be set.

.SH DESCRIPTION
This utility will set update your Nest's "away" setting, noting that you're either home or away, depending on how you invoke it.

.SH FILES
You need to set up a file at \fI~/.uhome/nest.yaml\fP with your Nest credentials:

	$ cat ~/.uhome/nest.yaml

	username: "your-email@example.com"

	password: "1-2-3-4-5"

.SH EXAMPLES

	$ nest-away

	Nest updated -->  away=True

	$ nest-home

	Nest updated -->  away=False

.SH SEE ALSO
\fBuhome\fP(1)

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <dustin.kirkland@gmail.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the Apache2 License.

The complete text of the Apache2 License can be found in \fI/usr/share/common-licenses/Apache-2.0\fP on Debian/Ubuntu systems.
