.TH uhome-nest-update 1 "30 January 2015" uhome "uhome"
.SH NAME
uhome-nest-update\- tests whether or not you're home, based on device presence, and then updates your Nest

.SH SYNOPSIS
\fBuhome-nest-update\fP

.SH DESCRIPTION

This utility will use the \fBuhome\fP(1) command to test if you're home or not, and update your Nest accordingly.

Note that you will need to configure your NEST_USERNAME and NEST_PASSWORD in \fI~/.uhome/uhomerc\fP.  Optionally, you can also set a NEST_EMAIL variable, and you'll receive email notices when this utility updates your Nest.

.SH SEE ALSO
\fBuhome\fP(1), \fBnest-home\fP(1), \fBnest-away\fP(1)

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <dustin.kirkland@gmail.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the Apache2 License.

The complete text of the Apache2 License can be found in \fI/usr/share/common-licenses/Apache-2.0\fP on Debian/Ubuntu systems.
